# Project: movie
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o linked_List.o movie.o
LINKOBJ  = main.o linked_List.o movie.o
LIBS     = -L"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Administrator/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = movie.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

linked_List.o: linked_List.c
	$(CC) -c linked_List.c -o linked_List.o $(CFLAGS)

movie.o: movie.c
	$(CC) -c movie.c -o movie.o $(CFLAGS)
